version: "3.8"

services:
  ${SERVICE_NAME}:
    build:
      context: .
    working_dir: /workdir
    volumes:
      - .:/workdir
    environment:
      HOST_WORKDIR: ${HOST_WORKDIR}

    # Uncomment the next line if you want to use the Podman socket in the container
    # volumes:
    #   - /run/user/1000/podman/podman.sock:/run/podman/podman.sock:Z
    # environment:
    #   Uncomment if using the Podman socket
    #   PODMAN_SOCKET: /run/podman/podman.sock

    security_opt:
      - label=disable
    stdin_open: true
    tty: true