version: "3.8"

services:
  rake_service:
    build:
      context: .
    working_dir: /workdir
    volumes:
      - .:/workdir
      

    environment:
      HOST_WORKDIR: ${HOST_WORKDIR}
      

    security_opt:
      - label=disable
    stdin_open: true
    tty: true
