require 'rake/clean'
require 'io/console'

# Define the default task
task default: :info

# Define a task
task :info do
    sh "podman-remote run --rm hello-world"
    puts "HOST_WORKDIR=#{ENV['HOST_WORKDIR']}"
end
