#!/usr/bin/env bash

set -e

cd "$(dirname "${BASH_SOURCE[0]}")" # Change to the directory of this script

substitute() {
    sed "s|$1|$2|g" "$3" -i
}

generate_compose_file() {
    local out_file="$1"
    local mount_socket="$2"
    local client_socket="$3"

    cp podman-compose.yml.in "$out_file"
    substitute "@MESSAGE@"       "DO NOT EDIT THIS FILE. This file is auto-generated." "$out_file"
    substitute "@MOUNT_SOCKET@"  "$mount_socket"                                       "$out_file"
    substitute "@PODMAN_SOCKET@" "$client_socket"                                      "$out_file"
}

# podman-compose with podman-remote
mount_socket="- /run/user/1000/podman/podman.sock:/run/podman/podman.sock:Z"
client_socket="PODMAN_SOCKET: /run/podman/podman.sock"
generate_compose_file "../podman-compose.yml.with-remote" "$mount_socket" "$client_socket"

# podman-compose without podman-remote
generate_compose_file "../podman-compose.yml.without-remote"
