#!/usr/bin/env bash

set -e

cd "$(dirname "${BASH_SOURCE[0]}")" # Change to the directory of this script

generate_compose_file() {
    local out_file="$1"
    local mount_socket="$2"
    local client_socket="$3"
    local message=$4

    cp podman-compose.yml.in "$out_file"
    sed "s|@MESSAGE@|DO NOT EDIT THIS FILE. This file is auto-generated.|g"             "$out_file" -i
    sed "s|@MOUNT_SOCKET@|$mount_socket|g"   "$out_file" -i
    sed "s|@PODMAN_SOCKET@|$client_socket|g" "$out_file" -i
}

# podman-compose with podman-remote
mount_socket="- /run/user/1000/podman/podman.sock:/run/podman/podman.sock:Z"
client_socket="PODMAN_SOCKET: /run/podman/podman.sock"
generate_compose_file "../podman-compose.yml.with-remote" "$mount_socket" "$client_socket"

# podman-compose without podman-remote
generate_compose_file "../podman-compose.yml.no-remote"

pushd ..

read -p "Do you want to use podman-remote in Rakefile? [y/N]: " use_remote
if [[ "$use_remote" =~ ^[y]$ ]]; then
    ln -sf podman-compose.yml.with-remote podman-compose.yml
    RAKE_TASK="hello_podman"
else
    ln -sf podman-compose.yml.no-remote podman-compose.yml
fi

./rake.sh $RAKE_TASK
