FROM registry.fedoraproject.org/fedora-minimal:latest

# Install any additional packages you need
RUN dnf -y install ruby rubygems @PODMAN_REMOTE@ && \
    dnf clean all && \
    gem install rake

WORKDIR /workdir

ENTRYPOINT ["rake"]
